Use simple rust development environment instead of the complex docker in CI.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,31 +1,34 @@
-language: generic
-sudo: required
-cache:
-  timeout: 600
-  directories:
-    - $TRAVIS_BUILD_DIR/target
-    - $HOME/.cargo/git
-    - $HOME/.cargo/registry
-services:
-  - docker
-git:
-  depth: 1
-install:
-  - bash '.ci-scripts/install-env'
+dist: xenial
+language: rust
+addons:
+  apt:
+    packages:
+    - libsnappy-dev
+    - libgoogle-perftools-dev
 stages:
-  - Format
+  - Check
   - Test
 jobs:
   include:
-    - stage: Format
-      script: bash '.ci-scripts/format'
-    - stage: Test
-      name: Test
-      env: CACHE_NAME=Test
+    - stage: Check
+      name: Format
       script:
-        - bash '.ci-scripts/test'
-        - bash '.ci-scripts/check-cargolock'
-    - stage: Test
+        - rustup component add rustfmt
+        - cargo fmt --all -- --check
+    - stage: Check
       name: Clippy
-      env: CACHE_NAME=Clippy
-      script: bash '.ci-scripts/clippy'
+      env: RUSTFLAGS='-F warnings'
+      script:
+        - rustup component add clippy
+        - cargo clippy --all --all-targets
+        - |
+            if [ $(git status --short Cargo.lock | wc -l) -ne 0 ]; then
+                echo "[Error] Please update Cargo.lock BEFORE commit."
+                git diff Cargo.lock
+                exit 1
+            fi
+    - stage: Test
+      name: Unit Test
+      env: RUSTFLAGS='-F warnings'
+      script:
+        - cargo test --all --verbose
